services:
  mariadb:
    environment:
      MYSQL_DATABASE: projectrunner
      MYSQL_PASSWORD: projectrunnerpassword
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: projectrunnerdbuser
    image: mariadb
    network_mode: host
    volumes:
    - /home/idan/project-runner-backend/dev/mariadb.cnf:/etc/mysql/my.cnf:rw
version: '3.0'
